import type { Gene, Protein, Transcript, Variant } from '../models/scientific';
import { t } from '../i18n';
import { renderEvidence } from './evidence';

const safe = (value: string | number): string => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const valueOr = (value: string | number | undefined): string => value === undefined || value === '' ? t('explorer.noData') : safe(value);
const renderDl = (entries: Array<[string, string]>): string => `<dl class="metadata">${entries.map(([label, value]) => `<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl>`;

export const renderDemoBanner = (mode: 'demo' | 'live'): string => `<div class="data-banner ${mode === 'demo' ? 'is-demo' : 'is-live'}" role="status"><strong>${mode === 'demo' ? t('explorer.demoBanner') : t('explorer.liveData')}</strong></div>`;

export const renderGeneCard = (gene: Gene): string => `<article class="result-card"><div><span class="entity-label">${t('explorer.gene')}</span><h3>${safe(gene.symbol)}</h3><p>${safe(gene.name)}</p></div><div class="result-meta"><span>${safe(gene.organism)}</span><a class="text-link" href="#/gene/${encodeURIComponent(gene.id)}">${t('explorer.details')} -&gt;</a></div></article>`;

const renderNcbiMetadata = (gene: Gene): string => `<section class="data-panel"><div class="panel-heading"><p class="eyebrow">NCBI Gene</p><h2>${t('explorer.evidence')}</h2></div>${renderDl([[t('explorer.mapLocation'), valueOr(gene.mapLocation)], [t('explorer.recordStatus'), valueOr(gene.recordStatus)], [t('explorer.createdAt'), valueOr(gene.createdAt)], [t('explorer.updatedAt'), valueOr(gene.updatedAt)], [t('explorer.designations'), valueOr(gene.designations?.join('; '))], [t('explorer.genomicAccessions'), valueOr(gene.genomicAccessions?.join(', '))]])}</section>`;

export const renderSearchPage = (genes: Gene[], query: string, mode: 'demo' | 'live'): string => `<section class="explorer-page" aria-labelledby="search-title">${renderDemoBanner(mode)}<div class="explorer-heading"><p class="eyebrow">02 / ${t('nav.genes')}</p><h1 id="search-title">${t('explorer.searchTitle')}</h1><p>${t('explorer.searchHelp')}</p></div><form class="explorer-search" id="gene-search-form"><label class="sr-only" for="gene-query">${t('explorer.searchTitle')}</label><input id="gene-query" name="query" type="search" value="${safe(query)}" placeholder="${t('explorer.searchPlaceholder')}" autocomplete="off"><button type="submit">${t('explorer.search')}</button></form><section class="results-section" aria-labelledby="results-title"><div class="section-heading-inline"><h2 id="results-title">${t('explorer.results')}</h2><span>${genes.length}</span></div>${genes.length ? `<div class="result-grid">${genes.map(renderGeneCard).join('')}</div>` : `<p class="empty-state">${t('explorer.noResults')}</p>`}</section></section>`;

export const renderGeneDetails = (gene: Gene, mode: 'demo' | 'live' = 'live'): string => `<section class="explorer-page" aria-labelledby="gene-title">${renderDemoBanner(mode)}<a class="back-link" href="#/genes">&lt;- ${t('nav.genes')}</a><div class="record-heading"><div><p class="eyebrow">${t('explorer.gene')}</p><h1 id="gene-title">${safe(gene.symbol)}</h1><p>${safe(gene.name)}</p></div><div class="record-actions"><span class="record-id">${safe(gene.id)}</span><a class="action-link" href="#/variants?gene=${encodeURIComponent(gene.id)}${mode === 'demo' ? '&demo=1' : ''}">${t('explorer.exploreVariants')} -&gt;</a></div></div><div class="record-grid"><section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.identity')}</p><h2>${safe(gene.symbol)}</h2></div>${renderDl([[t('explorer.organism'), safe(gene.organism)], [t('explorer.aliases'), gene.aliases.length ? gene.aliases.map(safe).join(', ') : t('explorer.noData')], [t('explorer.externalIds'), Object.keys(gene.externalIdentifiers).length ? Object.entries(gene.externalIdentifiers).map(([key, value]) => `${safe(key)}: ${safe(value)}`).join(', ') : t('explorer.noData')], [t('explorer.geneType'), valueOr(gene.geneType)]])}</section><section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.genomics')}</p><h2>${valueOr(gene.location?.assembly)}</h2></div>${renderDl([[t('explorer.assembly'), valueOr(gene.location?.assembly)], [t('explorer.location'), gene.location ? `${safe(gene.location.chromosome)}:${valueOr(gene.location.start)}-${valueOr(gene.location.end)} (${safe(gene.location.strand ?? '?')})` : t('explorer.noData')]])}</section></div>${renderNcbiMetadata(gene)}<section class="data-panel function-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.function')}</p><h2>${t('explorer.gene')}</h2></div><p>${valueOr(gene.description)}</p></section>${renderTranscripts(gene.transcripts)}${renderProteins(gene.proteins)}${renderEvidence(gene.sources)}</section>`;

export const renderVariantExplorer = (gene: Gene | undefined, variants: Variant[], selectedType = '', selectedConsequence = '', mode: 'demo' | 'live' = 'live', query = '', noResult = false): string => `<section class="explorer-page" aria-labelledby="variant-explorer-title">${renderDemoBanner(mode)}<div class="explorer-heading"><p class="eyebrow">${t('nav.variants')}</p><h1 id="variant-explorer-title">${t('explorer.variantExplorerTitle')}</h1><p>${t('explorer.variantSearchHelp')}</p><form class="explorer-search variant-search" id="variant-search-form"><label class="sr-only" for="variant-query">${t('explorer.variantSearchTitle')}</label><input id="variant-query" name="query" type="search" value="${safe(query)}" placeholder="${t('explorer.variantSearchPlaceholder')}" autocomplete="off"><button type="submit">${t('explorer.search')}</button></form></div>${gene ? `<a class="back-link" href="#/gene/${encodeURIComponent(gene.id)}">&lt;- ${t('explorer.backGene')}</a><div class="record-heading variant-record-heading"><div><p class="eyebrow">${t('explorer.variantExplorerTitle')}</p><h2>${safe(gene.symbol)}</h2></div><span class="record-id">${safe(gene.id)}</span></div>${renderVariantControls(variants, selectedType, selectedConsequence)}${renderVariantTable(variants)}` : `<div class="placeholder"><p>${noResult ? t('explorer.variantSearchNoResult') : t('explorer.selectGene')}</p></div>`}</section>`;

const renderVariantControls = (variants: Variant[], selectedType: string, selectedConsequence: string): string => {
	const types = [...new Set(variants.map((variant) => variant.variantType))];
	const consequences = [...new Set(variants.map((variant) => variant.consequence).filter((value): value is string => Boolean(value)))];
	return `<form class="filter-panel" id="variant-filters"><div><p class="eyebrow">${t('explorer.variantFilters')}</p><h2>${t('explorer.variants')}</h2></div><label>${t('explorer.type')}<select name="type"><option value="">${t('explorer.allTypes')}</option>${types.map((type) => `<option value="${safe(type)}" ${type === selectedType ? 'selected' : ''}>${safe(type)}</option>`).join('')}</select></label><label>${t('explorer.consequence')}<select name="consequence"><option value="">${t('explorer.allConsequences')}</option>${consequences.map((consequence) => `<option value="${safe(consequence)}" ${consequence === selectedConsequence ? 'selected' : ''}>${safe(consequence)}</option>`).join('')}</select></label><button type="submit">${t('explorer.search')}</button></form>`;
};

const renderTranscripts = (transcripts: Transcript[]): string => `<section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.transcripts')}</p><h2>${transcripts.length}</h2></div>${transcripts.length ? `<div class="compact-list">${transcripts.map((item) => `<div><strong>${safe(item.id)}</strong><span>${safe(item.source.name)}${item.status ? ` · ${safe(item.status)}` : ''}</span></div>`).join('')}</div>` : `<p class="empty-state">${t('explorer.noTranscripts')}</p>`}</section>`;

const renderProteins = (proteins: Protein[]): string => `<section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.proteins')}</p><h2>${proteins.length}</h2></div>${proteins.length ? `<div class="compact-list">${proteins.map((item) => `<div><strong>${safe(item.id)}</strong><span>${safe(item.name)}${item.aminoAcidLength ? ` · ${item.aminoAcidLength} aa` : ''}</span></div>`).join('')}</div>` : `<p class="empty-state">${t('explorer.noProteins')}</p>`}</section>`;

export const renderVariantTable = (variants: Variant[]): string => `<section class="data-panel variant-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.variants')}</p><h2>${variants.length}</h2></div>${variants.length ? `<div class="table-wrap"><table><caption class="sr-only">${t('explorer.variants')}</caption><thead><tr><th scope="col">${t('explorer.variantId')}</th><th scope="col">${t('explorer.type')}</th><th scope="col">${t('explorer.consequence')}</th><th scope="col">${t('explorer.transcriptChange')}</th><th scope="col">${t('explorer.details')}</th></tr></thead><tbody>${variants.map((variant) => `<tr><th scope="row">${safe(variant.id)}</th><td>${valueOr(variant.variantType)}</td><td>${valueOr(variant.consequence)}</td><td>${valueOr(variant.transcriptChange)}</td><td><a class="text-link" href="#/variant/${encodeURIComponent(variant.id)}">-&gt;</a></td></tr>`).join('')}</tbody></table></div>` : `<p class="empty-state">${t('explorer.noVariants')}</p>`}</section>`;

export const renderVariantDetails = (variant: Variant, gene?: Gene, mode: 'demo' | 'live' = 'demo'): string => `<section class="explorer-page" aria-labelledby="variant-title">${renderDemoBanner(mode)}<a class="back-link" href="#/gene/${encodeURIComponent(gene?.id ?? variant.geneId)}">&lt;- ${t('explorer.backGene')}</a><div class="record-heading"><div><p class="eyebrow">${t('explorer.variant')}</p><h1 id="variant-title">${safe(variant.id)}</h1><p>${gene ? `${t('explorer.gene')}: ${safe(gene.symbol)}` : safe(variant.geneId)}</p></div><span class="record-id">${safe(variant.variantType)}</span></div><div class="record-grid"><section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.identity')}</p><h2>${safe(variant.id)}</h2></div>${renderDl([[t('explorer.gene'), gene?.symbol ?? variant.geneId], [t('explorer.type'), valueOr(variant.variantType)], [t('explorer.assembly'), valueOr(variant.location?.assembly)], [t('explorer.location'), variant.location ? `${safe(variant.location.chromosome)}:${valueOr(variant.location.start)}` : t('explorer.noData')]])}</section><section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.consequence')}</p><h2>${valueOr(variant.consequence)}</h2></div>${renderDl([[t('explorer.genomicChange'), valueOr(variant.genomicChange)], [t('explorer.transcriptChange'), valueOr(variant.transcriptChange)], [t('explorer.proteinChange'), valueOr(variant.proteinChange)]])}</section></div><section class="data-panel"><div class="panel-heading"><p class="eyebrow">${t('explorer.significance')}</p><h2>${valueOr(variant.clinicalSignificance)}</h2></div><p class="scientific-note">${t('explorer.clinicalNote')}</p>${renderDl([[t('explorer.frequency'), valueOr(variant.frequency)], [t('explorer.reviewStatus'), valueOr(variant.reviewStatus)], [t('explorer.condition'), valueOr(variant.condition)]])}</section>${renderEvidence(variant.evidence)}</section>`;