import type { Gene, Publication } from '../models/scientific';
import { plannedSources } from '../data/sources';
import { t } from '../i18n';
import { renderEvidence } from './evidence';
import type { SequenceAnalysis, SequenceComparison } from '../utils/sequence';
import { getNote } from '../utils/workspace';
import type { HistoryEntry, SavedItem } from '../utils/workspace';
import type { LocalAccount } from '../utils/accounts';
import type { ExperimentRecord } from '../utils/notebook';

const safe = (value: string): string => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export const renderLiteraturePage = (publications: Publication[], query: string): string => `<section class="explorer-page" aria-labelledby="literature-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.literature')}</p><h1 id="literature-title">${t('literature.title')}</h1><p>${t('literature.help')}</p><form class="explorer-search" id="literature-search-form"><label class="sr-only" for="literature-query">${t('literature.placeholder')}</label><input id="literature-query" name="query" type="search" value="${safe(query)}" placeholder="${t('literature.placeholder')}" autocomplete="off"><button type="submit">${t('explorer.search')}</button></form>${publications.length ? `<button class="action-button" id="export-literature" type="button">${t('literature.export')}</button>` : ''}</div><section class="result-grid literature-grid">${publications.length ? publications.map(renderPublication).join('') : `<p class="empty-state">${query ? t('literature.empty') : t('explorer.selectGene')}</p>`}</section></section>`;
const renderPublication = (publication: Publication): string => `<article class="result-card publication-card"><div><span class="entity-label">PubMed · ${publication.year ?? t('explorer.noData')}</span><h3>${safe(publication.title)}</h3><p>${t('literature.authors')}: ${safe(publication.authors.join(', ') || t('explorer.noData'))}</p><p>${t('literature.journal')}: ${safe(publication.journal ?? t('explorer.noData'))}</p>${publication.abstract ? `<p class="publication-abstract">${safe(publication.abstract)}</p>` : ''}${publication.source ? `<small class="source-note">${safe(publication.source.name)} · ${safe(publication.source.identifier ?? t('explorer.noData'))}</small>` : ''}</div><a class="text-link" href="${safe(publication.url ?? '#')}" target="_blank" rel="noopener noreferrer">${t('literature.open')} -&gt;</a></article>`;
 
const renderLabResults = (analysis: SequenceAnalysis): string => `${analysis.orfs?.length ? `<section class="data-panel analysis-block"><div class="panel-heading"><p class="eyebrow">${t('lab.orfs')}</p><h2>${analysis.orfs.length}</h2></div><div class="compact-list">${analysis.orfs.slice(0, 8).map((orf) => `<div><strong>${t('lab.frame')} ${orf.frame}</strong><span>${t('lab.position')} ${orf.start}-${orf.end} · ${safe(orf.protein)}</span></div>`).join('')}</div></section>` : ''}${analysis.restrictionSites?.length ? `<section class="data-panel analysis-block"><div class="panel-heading"><p class="eyebrow">${t('lab.restrictionSites')}</p><h2>${analysis.restrictionSites.length}</h2></div><div class="compact-list">${analysis.restrictionSites.map((site) => `<div><strong>${safe(site.enzyme)}</strong><span>${safe(site.recognitionSite)} · ${t('lab.position')} ${site.position}</span></div>`).join('')}</div></section>` : `<section class="data-panel analysis-block"><div class="panel-heading"><p class="eyebrow">${t('lab.restrictionSites')}</p><h2>0</h2></div><p class="empty-state">${t('lab.noRestrictionSites')}</p></section>`}${analysis.primers?.length ? `<section class="data-panel analysis-block"><div class="panel-heading"><p class="eyebrow">${t('lab.primers')}</p><h2>${analysis.primers.length}</h2></div><div class="compact-list">${analysis.primers.map((primer) => `<div><strong>${t(`lab.${primer.direction}`)}</strong><span class="sequence-value">${safe(primer.sequence)}</span><small>${primer.gcPercentage}% GC · ${primer.meltingTemperature} °C${primer.warnings.length ? ` · ${t('lab.reviewPrimer')}` : ''}</small></div>`).join('')}</div></section>` : ''}`;

export const renderLabPage = (analysis?: SequenceAnalysis, error = false, comparison?: SequenceComparison): string => `<section class="explorer-page" aria-labelledby="lab-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.lab')}</p><h1 id="lab-title">${t('lab.title')}</h1><p>${t('lab.help')}</p></div><form class="lab-form" id="sequence-form"><label for="sequence-input">${t('lab.sequence')}</label><textarea id="sequence-input" name="sequence" rows="8" spellcheck="false"></textarea><label for="comparison-input">${t('lab.comparisonSequence')}</label><textarea id="comparison-input" name="comparison" rows="5" spellcheck="false"></textarea><button type="submit">${t('lab.analyze')}</button></form>${error ? `<p class="error-state" role="alert">${t('lab.invalid')}</p>` : analysis ? `<section class="data-panel analysis-panel"><div class="panel-heading"><p class="eyebrow">${t('lab.summary')}</p><button class="action-button" id="export-analysis" type="button">${t('lab.export')}</button></div><div class="metadata"><div><dt>${t('lab.alphabet')}</dt><dd>${safe(analysis.alphabet)}</dd></div><div><dt>${t('lab.length')}</dt><dd>${analysis.length}</dd></div><div><dt>${t('lab.gc')}</dt><dd>${analysis.gcPercentage}%</dd></div>${analysis.alphabet === 'DNA' ? `<div class="gc-meter" aria-label="${t('lab.gcProfile')}"><span style="width: ${analysis.gcPercentage}%"></span></div>` : ''}${analysis.transcription ? `<div><dt>${t('lab.transcription')}</dt><dd class="sequence-value">${safe(analysis.transcription)}</dd></div>` : ''}${analysis.reverseComplement ? `<div><dt>${t('lab.reverseComplement')}</dt><dd class="sequence-value">${safe(analysis.reverseComplement)}</dd></div>` : ''}${analysis.translation ? `<div><dt>${t('lab.translation')}</dt><dd class="sequence-value">${safe(analysis.translation)}</dd></div>` : ''}</div></section>${renderLabResults(analysis)}${comparison ? `<section class="data-panel analysis-block"><div class="panel-heading"><p class="eyebrow">${t('lab.comparison')}</p><h2>${comparison.identityPercentage}%</h2></div><div class="metadata"><div><dt>${t('lab.referenceLength')}</dt><dd>${comparison.referenceLength}</dd></div><div><dt>${t('lab.queryLength')}</dt><dd>${comparison.queryLength}</dd></div><div><dt>${t('lab.differences')}</dt><dd>${comparison.differences.length}</dd></div></div>${comparison.differences.length ? `<div class="table-wrap"><table><thead><tr><th>${t('lab.position')}</th><th>${t('lab.reference')}</th><th>${t('lab.query')}</th></tr></thead><tbody>${comparison.differences.slice(0, 100).map((difference) => `<tr><th>${difference.position}</th><td>${safe(difference.reference)}</td><td>${safe(difference.query)}</td></tr>`).join('')}</tbody></table></div>` : `<p class="empty-state">${t('lab.noDifferences')}</p>`}</section>` : ''}` : ''}</section>`;
 
export const renderAssistantPage = (gene?: Gene, query = ''): string => `<section class="explorer-page" aria-labelledby="assistant-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.assistant')}</p><h1 id="assistant-title">${t('assistant.title')}</h1><p>${t('assistant.help')}</p><form class="explorer-search" id="assistant-search-form"><label class="sr-only" for="assistant-query">${t('assistant.placeholder')}</label><input id="assistant-query" name="query" type="search" value="${safe(query)}" placeholder="${t('assistant.placeholder')}" autocomplete="off"><button type="submit">${t('assistant.search')}</button></form></div>${gene ? `<section class="data-panel assistant-result"><div class="panel-heading"><p class="eyebrow">${t('assistant.verified')}</p><h2>${safe(gene.symbol)} · ${safe(gene.name)}</h2></div><p>${safe(gene.description ?? t('explorer.noData'))}</p>${renderEvidence(gene.sources)}</section>` : ''}<aside class="notice"><div><p class="eyebrow">${t('assistant.limits')}</p><p>${t('assistant.limitText')}</p></div></aside></section>`;
 
export const renderAboutPage = (): string => `<section class="placeholder content-page" aria-labelledby="about-title"><p class="eyebrow">${t('nav.about')}</p><h1 id="about-title">${t('about.title')}</h1><p>${t('about.mission')}</p><section class="data-panel"><h2>${t('about.method')}</h2><p>${t('about.methodText')}</p></section><section class="data-panel"><h2>${t('about.safety')}</h2><p>${t('about.safetyText')}</p></section></section>`;
export const renderSourcesPage = (): string => `<section class="explorer-page content-page" aria-labelledby="sources-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.sources')}</p><h1 id="sources-title">${t('sources.title')}</h1><p>${t('sources.help')}</p></div>${renderEvidence(plannedSources)}</section>`;

const renderSavedCard = (item: SavedItem): string => `<article class="result-card workspace-card"><div><span class="entity-label">${t(`workspace.${item.kind}`)}</span><h3>${safe(item.label)}</h3><p>${safe(item.subtitle)}</p></div><div class="result-meta"><span>${safe(item.id)}</span><a class="text-link" href="#/${item.kind}/${encodeURIComponent(item.id)}">${t('explorer.details')} -&gt;</a></div></article>`;

export const renderWorkspacePage = (items: SavedItem[], history: HistoryEntry[], compare = false): string => `<section class="explorer-page content-page" aria-labelledby="workspace-title"><div class="explorer-heading"><p class="eyebrow">${compare ? t('workspace.compareEyebrow') : t('nav.saved')}</p><h1 id="workspace-title">${compare ? t('workspace.compareTitle') : t('workspace.title')}</h1><p>${compare ? t('workspace.compareHelp') : `${t('workspace.help')} <a class="text-link" href="#/compare">${t('workspace.compareTitle')} -&gt;</a>`}</p></div>${compare ? items.length >= 2 ? `<section class="data-panel compare-panel"><div class="panel-heading"><p class="eyebrow">${t('workspace.compareSelected')}</p><h2>${items.length}</h2></div><div class="table-wrap"><table><caption class="sr-only">${t('workspace.compareTitle')}</caption><thead><tr><th>${t('workspace.field')}</th>${items.slice(0, 4).map((item) => `<th>${safe(item.label)}</th>`).join('')}</tr></thead><tbody><tr><th>${t('workspace.kind')}</th>${items.slice(0, 4).map((item) => `<td>${t(`workspace.${item.kind}`)}</td>`).join('')}</tr><tr><th>${t('workspace.identifier')}</th>${items.slice(0, 4).map((item) => `<td>${safe(item.id)}</td>`).join('')}</tr><tr><th>${t('workspace.description')}</th>${items.slice(0, 4).map((item) => `<td>${safe(item.subtitle)}</td>`).join('')}</tr></tbody></table></div></section>` : `<p class="empty-state">${t('workspace.compareEmpty')}</p>` : `<section class="result-grid workspace-grid">${items.length ? items.map(renderSavedCard).join('') : `<p class="empty-state">${t('workspace.empty')}</p>`}</section><section class="data-panel history-panel"><div class="panel-heading"><p class="eyebrow">${t('workspace.history')}</p><h2>${history.length}</h2></div>${history.length ? `<div class="compact-list">${history.map((entry) => `<div><strong>${safe(entry.label)}</strong><a class="text-link" href="${safe(entry.href)}">${t('workspace.reopen')} -&gt;</a></div>`).join('')}</div>` : `<p class="empty-state">${t('workspace.noHistory')}</p>`}</section>`}</section>`;

export const renderWorkspaceSelectionPage = (items: SavedItem[], history: HistoryEntry[]): string => { const genes = items.filter((item) => item.kind === 'gene'); return `<section class="explorer-page content-page" aria-labelledby="workspace-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.saved')}</p><h1 id="workspace-title">${t('workspace.title')}</h1><p>${t('workspace.help')} <a class="text-link" href="#/compare">${t('workspace.compareTitle')} -&gt;</a></p></div><form class="workspace-selection" id="compare-selection-form"><div class="result-grid workspace-grid">${genes.length ? genes.map((item) => `<label class="result-card workspace-card selectable-card"><input type="checkbox" name="gene" value="${safe(item.id)}"><span><span class="entity-label">${t('workspace.gene')}</span><strong>${safe(item.label)}</strong><small>${safe(item.subtitle)} · ${safe(item.id)}</small></span></label>`).join('') : `<p class="empty-state">${t('workspace.empty')}</p>`}</div><button class="action-button" type="submit">${t('workspace.compareSelected')}</button></form><section class="data-panel history-panel"><div class="panel-heading"><p class="eyebrow">${t('workspace.history')}</p><h2>${history.length}</h2></div>${history.length ? `<div class="compact-list">${history.map((entry) => `<div><strong>${safe(entry.label)}</strong><a class="text-link" href="${safe(entry.href)}">${t('workspace.reopen')} -&gt;</a></div>`).join('')}</div>` : `<p class="empty-state">${t('workspace.noHistory')}</p>`}</section></section>`; };

export const renderWorkspaceSelectionWithNotes = (items: SavedItem[], history: HistoryEntry[]): string => { const genes = items.filter((item) => item.kind === 'gene'); return `<section class="explorer-page content-page" aria-labelledby="workspace-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.saved')}</p><h1 id="workspace-title">${t('workspace.title')}</h1><p>${t('workspace.help')} <a class="text-link" href="#/compare">${t('workspace.compareTitle')} -&gt;</a></p></div><form class="workspace-selection" id="compare-selection-form"><div class="result-grid workspace-grid">${genes.length ? genes.map((item) => `<div class="result-card workspace-card workspace-item"><label class="selectable-card"><input type="checkbox" name="gene" value="${safe(item.id)}"><span><span class="entity-label">${t('workspace.gene')}</span><strong>${safe(item.label)}</strong><small>${safe(item.subtitle)} · ${safe(item.id)}</small></span></label><label class="workspace-note-label" for="note-${safe(item.id)}">${t('workspace.note')}</label><textarea class="workspace-note" id="note-${safe(item.id)}" data-note-kind="gene" data-note-id="${safe(item.id)}" rows="3">${safe(getNote('gene', item.id))}</textarea><button class="action-button save-note" type="button" data-note-kind="gene" data-note-id="${safe(item.id)}">${t('workspace.saveNote')}</button></div>`).join('') : `<p class="empty-state">${t('workspace.empty')}</p>`}</div><button class="action-button" type="submit">${t('workspace.compareSelected')}</button></form><section class="data-panel history-panel"><div class="panel-heading"><p class="eyebrow">${t('workspace.history')}</p><h2>${history.length}</h2></div>${history.length ? `<div class="compact-list">${history.map((entry) => `<div><strong>${safe(entry.label)}</strong><a class="text-link" href="${safe(entry.href)}">${t('workspace.reopen')} -&gt;</a></div>`).join('')}</div>` : `<p class="empty-state">${t('workspace.noHistory')}</p>`}</section></section>`; };

const comparisonFields: Array<[string, (gene: Gene) => string | undefined]> = [
	['workspace.symbol', (gene) => gene.symbol], ['workspace.name', (gene) => gene.name], ['workspace.organism', (gene) => gene.organism], ['workspace.geneType', (gene) => gene.geneType], ['workspace.chromosome', (gene) => gene.chromosome],
	['workspace.mapLocation', (gene) => gene.mapLocation], ['workspace.assembly', (gene) => gene.location?.assembly], ['workspace.location', (gene) => gene.location ? `${gene.location.chromosome}:${gene.location.start ?? '?'}-${gene.location.end ?? '?'} ` : undefined], ['workspace.strand', (gene) => gene.location?.strand], ['workspace.recordStatus', (gene) => gene.recordStatus],
	['workspace.createdAt', (gene) => gene.createdAt], ['workspace.updatedAt', (gene) => gene.updatedAt], ['workspace.aliases', (gene) => gene.aliases.join(', ') || undefined], ['workspace.designations', (gene) => gene.designations?.join(', ')], ['workspace.genomicAccessions', (gene) => gene.genomicAccessions?.join(', ')],
];

export const renderGeneComparisonPage = (genes: Gene[]): string => `<section class="explorer-page content-page" aria-labelledby="comparison-title"><div class="explorer-heading"><p class="eyebrow">${t('workspace.compareEyebrow')}</p><h1 id="comparison-title">${t('workspace.compareTitle')}</h1><p>${t('workspace.compareHelp')}</p></div>${genes.length >= 4 ? `<section class="data-panel compare-panel"><div class="panel-heading"><p class="eyebrow">${t('workspace.compareSelected')}</p><h2>${genes.length}</h2></div><div class="table-wrap"><table class="comparison-table"><caption class="sr-only">${t('workspace.compareTitle')}</caption><thead><tr><th>${t('workspace.field')}</th>${genes.map((gene) => `<th>${safe(gene.symbol)}</th>`).join('')}</tr></thead><tbody>${comparisonFields.map(([key, getValue]) => `<tr><th>${t(key as Parameters<typeof t>[0])}</th>${genes.map((gene) => `<td>${safe(getValue(gene) ?? t('explorer.noData'))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>` : `<p class="empty-state">${t('workspace.compareMinimum')}</p>`}</section>`;

export const renderNotebookPage = (experiments: ExperimentRecord[]): string => `<section class="explorer-page content-page" aria-labelledby="notebook-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.notebook')}</p><h1 id="notebook-title">${t('notebook.title')}</h1><p>${t('notebook.help')}</p></div><form class="lab-form notebook-form" id="notebook-entry-form"><label for="notebook-entry-title">${t('notebook.experimentTitle')}</label><input id="notebook-entry-title" name="title" required placeholder="${t('notebook.experimentTitlePlaceholder')}"><label for="notebook-entry-notes">${t('notebook.notes')}</label><textarea id="notebook-entry-notes" name="notes" rows="4" placeholder="${t('notebook.notesPlaceholder')}"></textarea><label for="notebook-entry-references">${t('notebook.references')}</label><textarea id="notebook-entry-references" name="references" rows="3" placeholder="${t('notebook.referencesPlaceholder')}"></textarea><label for="notebook-entry-data">${t('notebook.dataPoints')} (${t('notebook.max20')})</label><textarea id="notebook-entry-data" name="dataPoints" rows="8" placeholder="${t('notebook.dataPointsPlaceholder')}"></textarea><button class="action-button" type="submit">${t('notebook.createEntry')}</button></form><section class="result-grid notebook-grid">${experiments.length ? experiments.map((experiment) => `<article class="result-card experiment-card"><div><span class="entity-label">${safe(experiment.id)}</span><h3>${safe(experiment.title)}</h3><p>${t('notebook.created')}: ${safe(new Date(experiment.createdAt).toLocaleString())}</p>${experiment.analysis ? `<p>${t('lab.length')}: ${experiment.analysis.length} · ${t('lab.gc')}: ${experiment.analysis.gcPercentage}%${experiment.comparison ? ` · ${t('lab.comparison')}: ${experiment.comparison.identityPercentage}%` : ''}</p>` : ''}${experiment.references.length ? `<p>${t('notebook.references')}: ${experiment.references.map((reference) => safe(reference.label)).join(', ')}</p>` : ''}${experiment.dataPoints.length ? `<dl class="experiment-data">${experiment.dataPoints.map((point) => `<div><dt>${safe(point.label)}</dt><dd>${safe(point.value)}</dd></div>`).join('')}</dl>` : ''}${experiment.notes ? `<p class="experiment-notes">${safe(experiment.notes)}</p>` : ''}</div><div class="result-meta"><button class="action-button export-experiment" type="button" data-experiment-id="${safe(experiment.id)}">${t('notebook.export')}</button><button class="action-button delete-experiment" type="button" data-experiment-id="${safe(experiment.id)}">${t('notebook.delete')}</button></div></article>`).join('') : `<p class="empty-state">${t('notebook.empty')}</p>`}</section></section>`;

export const renderAccountPage = (account?: LocalAccount): string => `<section class="explorer-page content-page" aria-labelledby="account-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.account')}</p><h1 id="account-title">${account ? t('account.profile') : t('account.title')}</h1><p>${t('account.help')}</p></div>${account ? `<section class="data-panel account-panel"><div class="panel-heading"><p class="eyebrow">${t('account.local')}</p><h2>${safe(account.email)}</h2></div><dl class="metadata"><div><dt>${t('account.created')}</dt><dd>${safe(new Date(account.createdAt).toLocaleString())}</dd></div><div><dt>${t('account.storage')}</dt><dd>${t('account.storageText')}</dd></div></dl><button class="action-button" id="logout-account" type="button">${t('account.logout')}</button></section>` : `<form class="lab-form account-form" id="account-form"><label for="account-email">${t('account.email')}</label><input id="account-email" name="email" type="email" autocomplete="email" required><label for="account-password">${t('account.password')}</label><input id="account-password" name="password" type="password" minlength="8" autocomplete="new-password" required><button class="action-button" type="submit">${t('account.create')}</button><p class="account-switch">${t('account.existing')} <button class="text-button" id="account-login-mode" type="button">${t('account.login')}</button></p><p class="source-note">${t('account.localWarning')}</p></form>`}</section>`;