import type { Gene, Publication } from '../models/scientific';
import { plannedSources } from '../data/sources';
import { t } from '../i18n';
import { renderEvidence } from './evidence';
import type { SequenceAnalysis } from '../utils/sequence';

const safe = (value: string): string => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export const renderLiteraturePage = (publications: Publication[], query: string): string => `<section class="explorer-page" aria-labelledby="literature-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.literature')}</p><h1 id="literature-title">${t('literature.title')}</h1><p>${t('literature.help')}</p><form class="explorer-search" id="literature-search-form"><label class="sr-only" for="literature-query">${t('literature.placeholder')}</label><input id="literature-query" name="query" type="search" value="${safe(query)}" placeholder="${t('literature.placeholder')}" autocomplete="off"><button type="submit">${t('explorer.search')}</button></form></div><section class="result-grid literature-grid">${publications.length ? publications.map(renderPublication).join('') : `<p class="empty-state">${query ? t('literature.empty') : t('explorer.selectGene')}</p>`}</section></section>`;
const renderPublication = (publication: Publication): string => `<article class="result-card publication-card"><div><span class="entity-label">PubMed · ${publication.year ?? t('explorer.noData')}</span><h3>${safe(publication.title)}</h3><p>${t('literature.authors')}: ${safe(publication.authors.join(', ') || t('explorer.noData'))}</p><p>${t('literature.journal')}: ${safe(publication.journal ?? t('explorer.noData'))}</p></div><a class="text-link" href="${safe(publication.url ?? '#')}" target="_blank" rel="noopener noreferrer">${t('literature.open')} -&gt;</a></article>`;
 
export const renderLabPage = (analysis?: SequenceAnalysis, error = false): string => `<section class="explorer-page" aria-labelledby="lab-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.lab')}</p><h1 id="lab-title">${t('lab.title')}</h1><p>${t('lab.help')}</p></div><form class="lab-form" id="sequence-form"><label for="sequence-input">${t('lab.sequence')}</label><textarea id="sequence-input" name="sequence" rows="8" spellcheck="false"></textarea><button type="submit">${t('lab.analyze')}</button></form>${error ? `<p class="error-state" role="alert">${t('lab.invalid')}</p>` : analysis ? `<section class="data-panel analysis-panel"><div class="metadata"><div><dt>${t('lab.alphabet')}</dt><dd>${safe(analysis.alphabet)}</dd></div><div><dt>${t('lab.length')}</dt><dd>${analysis.length}</dd></div><div><dt>${t('lab.gc')}</dt><dd>${analysis.gcPercentage}%</dd></div>${analysis.transcription ? `<div><dt>${t('lab.transcription')}</dt><dd class="sequence-value">${safe(analysis.transcription)}</dd></div>` : ''}${analysis.reverseComplement ? `<div><dt>${t('lab.reverseComplement')}</dt><dd class="sequence-value">${safe(analysis.reverseComplement)}</dd></div>` : ''}${analysis.translation ? `<div><dt>${t('lab.translation')}</dt><dd class="sequence-value">${safe(analysis.translation)}</dd></div>` : ''}</div></section>` : ''}</section>`;
 
export const renderAssistantPage = (gene?: Gene, query = ''): string => `<section class="explorer-page" aria-labelledby="assistant-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.assistant')}</p><h1 id="assistant-title">${t('assistant.title')}</h1><p>${t('assistant.help')}</p><form class="explorer-search" id="assistant-search-form"><label class="sr-only" for="assistant-query">${t('assistant.placeholder')}</label><input id="assistant-query" name="query" type="search" value="${safe(query)}" placeholder="${t('assistant.placeholder')}" autocomplete="off"><button type="submit">${t('assistant.search')}</button></form></div>${gene ? `<section class="data-panel assistant-result"><div class="panel-heading"><p class="eyebrow">${t('assistant.verified')}</p><h2>${safe(gene.symbol)} · ${safe(gene.name)}</h2></div><p>${safe(gene.description ?? t('explorer.noData'))}</p>${renderEvidence(gene.sources)}</section>` : ''}<aside class="notice"><div><p class="eyebrow">${t('assistant.limits')}</p><p>${t('assistant.limitText')}</p></div></aside></section>`;
 
export const renderAboutPage = (): string => `<section class="placeholder content-page" aria-labelledby="about-title"><p class="eyebrow">${t('nav.about')}</p><h1 id="about-title">${t('about.title')}</h1><p>${t('about.mission')}</p><section class="data-panel"><h2>${t('about.method')}</h2><p>${t('about.methodText')}</p></section><section class="data-panel"><h2>${t('about.safety')}</h2><p>${t('about.safetyText')}</p></section></section>`;
export const renderSourcesPage = (): string => `<section class="explorer-page content-page" aria-labelledby="sources-title"><div class="explorer-heading"><p class="eyebrow">${t('nav.sources')}</p><h1 id="sources-title">${t('sources.title')}</h1><p>${t('sources.help')}</p></div>${renderEvidence(plannedSources)}</section>`;